routes/admin.php
<?php
Route::get('/home', 'Admin\\AdminController@home')->name('admin.home');
Route::get('/', 'Admin\\AdminController@home')->name('admin.home');

Route::match(['get', 'post'], '/chpassword', 'Admin\\AdminController@changePassword');
Route::match(['get', 'post'], '/chemail', 'Admin\\AdminController@changeEmail');

Route::group(['middleware' => ['rols'], 'rols' => ['settings' => ['update']]], function () {
    Route::match(['get', 'post'], '/settings', 'Admin\AdminController@appSettings');
});


/** Posts Route  */
Route::group(['middleware' => ['rols'], 
              'service'    => ['service' => ['read']],
              'page'       => ['page' => ['read']],
              'blog'       => ['blog' => ['read']],
              'our_values' => ['our_values' => ['read']],
              'course'     => ['course' => ['read']]
             ], function () {
    Route::resource('/posts', 'Admin\PostController', ['only' => ['index']]);
});
Route::post('setStatus/{post}', 'Admin\AdminController@setStatus');

Route::group(['middleware' => ['rols'], 
              'service'    => ['service' => ['create']],
              'page'       => ['page' => ['create']],
              'blog'       => ['blog' => ['create']],
              'our_values' => ['our_values' => ['create']],
              'course'     => ['course' => ['create']]
          ], function () {
    Route::resource('/posts', 'Admin\PostController', ['only' => ['create']]);
});

Route::group(['middleware' => ['rols'], 
              'service'    => ['service' => ['create']],
              'page'       => ['page' => ['create']],
              'blog'       => ['blog' => ['create']],
              'our_values' => ['our_values' => ['create']],
              'course'     => ['course' => ['create']]
          ], function () {
    Route::resource('/posts', 'Admin\PostController', ['only' => ['store']]);
});

Route::group(['middleware' => ['rols'], 
              'service'    => ['service' => ['update']],
              'page'       => ['page' => ['update']],
              'blog'       => ['blog' => ['update']],
              'our_values' => ['our_values' => ['update']],
              'course'     => ['course' => ['update']]
             ], function () {
    Route::resource('/posts', 'Admin\PostController', ['only' => ['edit']]);
});

Route::group(['middleware' => ['rols'], 
              'service'    => ['service' => ['update']],
              'page'       => ['page' => ['update']],
              'blog'       => ['blog' => ['update']],
              'our_values' => ['our_values' => ['update']],
              'course'     => ['course' => ['update']]
          ], function () {
    Route::resource('/posts', 'Admin\PostController', ['only' => ['update']]);
});

Route::group(['middleware' => ['rols'], 
              'service'    => ['service' => ['delete']],
              'page'       => ['page' => ['delete']],
              'blog'       => ['blog' => ['delete']],
              'our_values' => ['our_values' => ['delete']],
              'course'     => ['course' => ['delete']]
          ], function () {
    Route::resource('/posts', 'Admin\PostController', ['only' => ['destroy']]);
});

// Route::group(['middleware' => ['rols']], function () {
//     Route::patch('/posts/toggle_status/{post}', 'Admin\PostController@toggleStatus');
// });


/** Categories Route  */
Route::group(['middleware' => ['rols'], 'rols' => ['category' => ['read']]], function () {
    Route::resource('/categories', 'Admin\CategoryController', ['only' => ['index']]);
});
Route::group(['middleware' => ['rols'], 'rols' => ['category' => ['create']]], function () {
    Route::resource('/categories', 'Admin\CategoryController', ['only' => ['create']]);
});
Route::group(['middleware' => ['rols'], 'rols' => ['category' => ['create']]], function () {
    Route::resource('/categories', 'Admin\CategoryController', ['only' => ['store']]);
});
Route::group(['middleware' => ['rols'], 'rols' => ['category' => ['update']]], function () {
    Route::resource('/categories', 'Admin\CategoryController', ['only' => ['edit']]);
});
Route::group(['middleware' => ['rols'], 'rols' => ['category' => ['delete']]], function () {
    Route::resource('/categories', 'Admin\CategoryController', ['only' => ['destroy']]);
});
Route::group(['middleware' => ['rols'], 'rols' => ['category' => ['update']]], function () {
    Route::resource('/categories', 'Admin\CategoryController', ['only' => ['update']]);
});


/** Admins Route  */
Route::group(['middleware' => ['rols'], 'rols' => ['admin' => ['read']]], function () {
    Route::resource('/admins', 'Admin\AdminController', ['only' => ['index']]);
});

Route::group(['middleware' => ['rols'], 'rols' => ['admin' => ['create']]], function () {
    Route::resource('/admins', 'Admin\AdminController', ['only' => ['create']]);
});

Route::group(['middleware' => ['rols'], 'rols' => ['admin' => ['create']]], function () {
    Route::resource('/admins', 'Admin\AdminController', ['only' => ['store']]);
});

Route::group(['middleware' => ['rols'], 'rols' => ['admin' => ['update']]], function () {
    Route::resource('/admins', 'Admin\AdminController', ['only' => ['edit']]);
});

Route::group(['middleware' => ['rols'], 'rols' => ['admin' => ['delete']]], function () {
    Route::resource('/admins', 'Admin\AdminController', ['only' => ['destroy']]);
});

Route::group(['middleware' => ['rols'], 'rols' => ['admin' => ['update']]], function () {
    Route::patch('/admins/toggle_status/{admin}', 'Admin\AdminController@toggleStatus');
});

Route::group(['middleware' => ['rols'], 'rols' => ['admin' => ['update']]], function () {
    Route::resource('/admins', 'Admin\AdminController', ['only' => ['update']]);
});

/** Banners Route  */
Route::group(['middleware' => ['rols'], 'rols' => ['banner' => ['read']]], function () {
    Route::resource('/banners', 'Admin\BannerController', ['only' => ['index']]);
});
Route::group(['middleware' => ['rols'], 'rols' => ['banner' => ['create']]], function () {
    Route::resource('/banners', 'Admin\BannerController', ['only' => ['create']]);
});
Route::group(['middleware' => ['rols'], 'rols' => ['banner' => ['create']]], function () {
    Route::resource('/banners', 'Admin\BannerController', ['only' => ['store']]);
});
Route::group(['middleware' => ['rols'], 'rols' => ['banner' => ['update']]], function () {
    Route::resource('/banners', 'Admin\BannerController', ['only' => ['edit']]);
});
Route::group(['middleware' => ['rols'], 'rols' => ['banner' => ['delete']]], function () {
    Route::resource('/banners', 'Admin\BannerController', ['only' => ['destroy']]);
});
Route::group(['middleware' => ['rols'], 'rols' => ['banner' => ['update']]], function () {
    Route::resource('/banners', 'Admin\BannerController', ['only' => ['update']]);
});

/** Trainers Route  */
Route::group(['middleware' => ['rols'], 'rols' => ['trainer' => ['read']]], function () {
    Route::resource('/trainers', 'Admin\TrainerController', ['only' => ['index']]);
});
Route::group(['middleware' => ['rols'], 'rols' => ['trainer' => ['create']]], function () {
    Route::resource('/trainers', 'Admin\TrainerController', ['only' => ['create']]);
});
Route::group(['middleware' => ['rols'], 'rols' => ['trainer' => ['create']]], function () {
    Route::resource('/trainers', 'Admin\TrainerController', ['only' => ['store']]);
});
Route::group(['middleware' => ['rols'], 'rols' => ['trainer' => ['update']]], function () {
    Route::resource('/trainers', 'Admin\TrainerController', ['only' => ['edit']]);
});
Route::group(['middleware' => ['rols'], 'rols' => ['trainer' => ['delete']]], function () {
    Route::resource('/trainers', 'Admin\TrainerController', ['only' => ['destroy']]);
});
Route::group(['middleware' => ['rols'], 'rols' => ['trainer' => ['update']]], function () {
    Route::resource('/trainers', 'Admin\TrainerController', ['only' => ['update']]);
});

/** Crtificates Route  */
Route::group(['middleware' => ['rols'], 'rols' => ['trainer' => ['read']]], function () {
    Route::resource('/certificates', 'Admin\CertificateController', ['only' => ['index']]);
});
Route::group(['middleware' => ['rols'], 'rols' => ['trainer' => ['create']]], function () {
    Route::resource('/certificates', 'Admin\CertificateController', ['only' => ['create']]);
});
Route::group(['middleware' => ['rols'], 'rols' => ['trainer' => ['create']]], function () {
    Route::resource('/certificates', 'Admin\CertificateController', ['only' => ['store']]);
});
Route::group(['middleware' => ['rols'], 'rols' => ['trainer' => ['update']]], function () {
    Route::resource('/certificates', 'Admin\CertificateController', ['only' => ['edit']]);
});
Route::group(['middleware' => ['rols'], 'rols' => ['trainer' => ['delete']]], function () {
    Route::resource('/certificates', 'Admin\CertificateController', ['only' => ['destroy']]);
});
Route::group(['middleware' => ['rols'], 'rols' => ['trainer' => ['update']]], function () {
    Route::resource('/certificates', 'Admin\CertificateController', ['only' => ['update']]);
});

/** Counters Route  */
Route::group(['middleware' => ['rols'], 'rols' => ['counter' => ['read']]], function () {
    Route::resource('/counters', 'Admin\CountersController', ['only' => ['index']]);
});
Route::group(['middleware' => ['rols'], 'rols' => ['counter' => ['create']]], function () {
    Route::resource('/counters', 'Admin\CountersController', ['only' => ['create']]);
});
Route::group(['middleware' => ['rols'], 'rols' => ['counter' => ['create']]], function () {
    Route::resource('/counters', 'Admin\CountersController', ['only' => ['store']]);
});
Route::group(['middleware' => ['rols'], 'rols' => ['counter' => ['update']]], function () {
    Route::resource('/counters', 'Admin\CountersController', ['only' => ['edit']]);
});
Route::group(['middleware' => ['rols'], 'rols' => ['counter' => ['delete']]], function () {
    Route::resource('/counters', 'Admin\CountersController', ['only' => ['destroy']]);
});

routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

/** Guest Available Routes */
Route::get('/', 'FrontController@index')->name('home');
Route::get('/home', 'FrontController@index')->name('home');

Route::get('/pg/{slug}', 'FrontController@page')->name('page');
Route::get('/services', 'FrontController@services')->name('services');
Route::get('/service/{service}', 'FrontController@service')->name('service');
Route::get('/courses/{category}', 'FrontController@courses')->name('courses');
Route::get('/course/{course}', 'FrontController@course')->name('course');
Route::get('/course/{course}/request', 'FrontController@courseRequest')->name('courseRequest');
Route::get('/contact', 'FrontController@contact')->name('contect');
Route::get('/blog', 'FrontController@blog')->name('blog');
Route::get('/post/{post}', 'FrontController@post')->name('post');
Route::get('/search', 'FrontController@search')->name('search');
Route::get('/trainers', 'FrontController@trainers')->name('trainers');
Route::get('/trainer/{trainer}', 'FrontController@trainer')->name('trainer');
Route::get('/certificate/{certificate}', 'FrontController@certificate')->name('certificate');
Route::get('/downloads', 'FrontController@downloads')->name('downloads');
Route::get('/videos', 'FrontController@videos')->name('videos');
Route::get('/gallery', 'FrontController@gallery')->name('gallery');
Route::get('/gallery/{gallery}', 'FrontController@galleryImages')->name('galleryImages');

Route::get('/profile', 'FrontController@profile')->name('profile');
Route::get('/mylibrary', 'FrontController@mylibrary')->name('mylibrary');
Route::get('/myfavorites', 'FrontController@myfavorites')->name('myfavorites');
Route::post('/addtomy','FrontController@addtomy')->name('addtomy');
Route::delete('/removefrommy','FrontController@removefrommy')->name('removefrommy');

Route::get('locale/{locale}', function ($locale) {
    \Session::put('locale', $locale);
});
Route::post('/servicemail', 'FrontController@servicemail')->name('servicemail');
Route::post('/contactmail', 'FrontController@contactmail')->name('contactmail');

Route::post('/autocomplete/fetchcpu','FrontController@fetchcpu')->name('autocomplete.fetchcpu');

/** Admin Auth Routes */
Route::get('admin/login', 'V1\Auth\AdminLoginController@showLoginForm')->name('admin.login');
Route::post('admin/login', 'V1\Auth\AdminLoginController@login')->name('admin.login.submit');

Route::get('admin/reset', 'V1\Auth\AdminLoginController@resetPassword')->name('admin.reset');
Route::post('admin/reset', 'V1\Auth\AdminLoginController@resetPassword')->name('admin.reset.submit');
Route::post('admin/logout', 'V1\Auth\AdminLoginController@logout')->name('admin.logout');

/** Client Auth Routes */
Route::get('register', function () {
	$bkg = rand(1,4);
	$title = __('front.register');
    return view('front.register')->with(compact('bkg', 'title'));
});
Route::post('register', 'V1\\Client\\ClientController@registerAction');

Route::get('login/{course?}', function ($course = 0) {
	$bkg = rand(1,4);
	$title = __('front.login');
	
    return view('front.login')->with(compact('bkg', 'title', 'course'));
})->name('client.login');

Route::get('resetpassword', 'V1\\Client\\ClientController@resetPasswordView')->name('client.resetpassword');
Route::post('login', 'V1\\Client\\ClientController@UserLogin');
Route::get('logout', 'V1\\Client\\ClientController@logout')->name('client.logout');
Route::post('resetpassword', 'V1\\Client\\ClientController@resetPassword');

Route::post('/requestaction/{course}', 'FrontController@requestaction')->name('requestaction');

app/Models/Common/Post.php
<?php

namespace App\Models\Common;

use App;
use Illuminate\Database\Eloquent\Model;

class Post extends Model
{
    protected $table = "posts";

    protected $guarded = [];

    public function postCategory()
    {
        return $this->belongsTo(Category::class, 'category', 'id');
    }

    public function getTitleAttribute()
    {
    	$local = App::getLocale();
        return $this->{ 'title_'.$local };
    }

    public function getContentAttribute()
    {
    	$local = App::getLocale();
        return $this->{ 'content_'.$local };
    }

    public function getShortDescAttribute()
    {
    	$local = App::getLocale();
        return $this->{ 'short_desc_'.$local };
    }

    public function getExtraAttribute()
    {
        return json_decode($this->extra_info, true);
    }

    public function postTrainer()
    {
        return $this->belongsTo(Trainer::class, 'trainer', 'id');
    }
}

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet" type="text/css">

    <!-- Styles -->
    <link href="{{ asset('public/css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light navbar-laravel">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            <li class="nav-item">
                                <a class="nav-link" href="{{ url('admin/login') }}">{{ __('Admin Login') }}</a>
                            </li>
                            <!-- <li class="nav-item">
                                <a class="nav-link" href="{{ url('client/login') }}">{{ __('Client Login') }}</a>
                            </li> -->
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
</body>
</html>

resources/views/layouts/menu-categories.blade.php
 @if ($category->home_page)
    <li class="{{ (( $share_locale == 'en' && $level > 1) || ( $share_locale == 'ar' )) ? 'drop-left' : '' }}">

        {{--
            @if( (count($category->children) > 0 || count($category->page) > 0) )
                <a href="#">{{ $category->name }}</a>
            @else
                <a href="{{ url('courses/'.$category->id) }}">{{ $category->name }}</a>
            @endif
        --}}

        <a href="{{ $category->clickable ? url('courses/'.$category->id) : '#' }}">
            {{ $category->name }}
            @if($level == 1)
            <br/>
            <span class="hint">{{ $category->short_desc }}</span>
            @endif 
        </a>
        

        @if ($category->children->count() > 0 || $category->page->count() > 0)
            <ul>
            @if ($category->page->count() > 0)
                @foreach($category->page as $page)
                    <a href="{{ url('pg/'.$page->slug) }}">{{ $page->title }}</a>
                @endforeach
            @endif 

            @if ($category->children->count() > 0)
                @foreach($category->children as $category)
                    @include('layouts.menu-categories', ['category' => $category, 'level' => $level+1])
                @endforeach
            @endif 

            @if($category->id == 21)
                <a href="{{ url('/services') }}">@lang('front.services')</a>
                <a href="{{ url('/trainers') }}">@lang('front.trainers')</a>
                <a href="{{ url('/videos') }}">@lang('front.videos')</a>
                <a href="{{ url('/gallery') }}">@lang('front.gallery')</a>
                <a href="{{ url('/downloads') }}">@lang('front.downloads')</a>
            @endif 
            </ul>
        @endif

       {{--
        @if ($category->page->count() > 0)
        	<ul>
            @foreach($category->page as $page)
                <a href="{{ url('pg/'.$page->slug) }}">{{ $page->title }}</a>
            @endforeach
            </ul>
        @endif    
        --}}    
    </li>
@endif